spring:
  config:
    import: vault://kv/applications/dev/${spring.application.name}
  cloud:
    vault:
      token: ${VAULT_TOKEN}
      authentication: TOKEN
      scheme: http
      host: vault
      port: 8200
      config:
        lifecycle:
          enabled: true


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs


