spring:
  application:
    name: NombreAppDebeCoinciderConVaultSecret
  output:
    ansi:
      enabled: always
  profiles:
    active: local
  config:
    location: ./src/main/resources
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  server:
    servlet:
      context-path: /flow-check/core
    port: 8080
keycloak:
   ssl-required: external
   useractive: 1
project:
   version: 0.0.1